day04/mod9/IceCreamCompany/IceCreamCompany/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace IceCreamCompany.Models
{
    public class Customer
    {
        public int CustomerId { get; set; }

        [Display(Name = "First Name")]
        [Required(ErrorMessage = "Please enter your first name")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Please enter your last name")]
        public string LastName { get; set; }

        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Please enter your email address")]
        public string Email { get; set; }

        [Display(Name = "Phone"), DataType(DataType.PhoneNumber)]
        public long PhoneNumber { get; set; }

        [Required(ErrorMessage = "Please enter your adress")]
        public string Address { get; set; }

        public virtual List<IceCreamFlavorsCustomers> IceCreamFlavors { get; set; }
    }
}

day04/mod9/IceCreamCompany/IceCreamCompany/Models/IceCream.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace IceCreamCompany.Models
{
    public class IceCream
    {
        public int IceCreamId { get; set; }

        [Range(1, 10)]
        [DataType(DataType.Currency)]
        public decimal Price { get; set; }

        [RegularExpression(@"^[A-Z]+[a-zA-Z""'\s-]*$")]
        [Required]
        [StringLength(30)]
        public string Flavor { get; set; }

        [DisplayName("Picture")]
        [MaxLength]
        public string PhotoFileName { get; set; }

        [HiddenInput(DisplayValue = false)]
        public string ImageMimeType { get; set; }

        public virtual List<IceCreamFlavorsCustomers> IceCreamFlavors { get; set; }
    }
}

day04/mod9/IceCreamCompany/IceCreamCompany/Models/IceCreamFlavorsCustomers.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IceCreamCompany.Models
{
    public class IceCreamFlavorsCustomers
    {
        public int IceCreamId { get; set; }
        public IceCream IceCream { get; set; }

        public int CustomerId { get; set; }
        public Customer Customer { get; set; }
    }
}

day04/mod9/IceCreamCompany/IceCreamCompany/Controllers/IceCreamController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using IceCreamCompany.Data;
using IceCreamCompany.Models;
using IceCreamCompany.Repositories;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace IceCreamCompany.Controllers
{
    public class IceCreamController : Controller
    {
        private IRepository _repository;
        private IHostingEnvironment _environment;

        public IceCreamController(IRepository repository, IHostingEnvironment environment)
        {
            _repository = repository;
            _environment = environment;
        }

        public IActionResult Index()
        {
            return View(_repository.GetIceCreamFlavors());
        }

        [HttpGet]
        public IActionResult Buy()
        {
            return View();
        }

        [HttpPost, ActionName("Buy")]
        public IActionResult BuyPost(Customer customer)
        {
            if (ModelState.IsValid)
            {
                _repository.BuyIceCreamFlavor(customer);
                return RedirectToAction(nameof(ThankYou));
            }
            return View(customer);
        }

        public IActionResult ThankYou()
        {
            return View();
        }

        public IActionResult GetImage(int iceCreamId)
        {
            IceCream requestedPhoto = _repository.GetIceCreamFlavorById(iceCreamId);
            if (requestedPhoto != null)
            {
                string webRootpath = _environment.WebRootPath;
                string folderPath = "\\images\\";
                string fullPath = webRootpath + folderPath + requestedPhoto.PhotoFileName;

                FileStream fileOnDisk = new FileStream(fullPath, FileMode.Open);
                byte[] fileBytes;
                using (BinaryReader br = new BinaryReader(fileOnDisk))
                {
                    fileBytes = br.ReadBytes((int)fileOnDisk.Length);
                }
                return File(fileBytes, requestedPhoto.ImageMimeType);
            }
            else
            {
                return NotFound();
            }
        }
    }
}

day04/mod9/IceCreamCompany/IceCreamCompany/Views/IceCream/Buy.cshtml
@model IceCreamCompany.Models.Customer
@{
    ViewData["Title"] = "Buy";
}

<div class="container">
    <h1>Choose Your Flavor</h1>
    <div class="checkout">
        <div class="row justify-content-center intro-row">
            <div class="col-4">Ice Cream Flavors</div>
            <div class="col-2">Buy Bulk(lbs)</div>
            <div class="col-2">Total Amount</div>
            <div class="col-2"></div>
        </div>
        <div class="row justify-content-center">
            <div class="col-4">
                <select class="form-control" id="flavor">
                    <option>Select</option>
                    <option>Vanilla Ice Cream with Caramel Ripple and Almonds</option>
                    <option>Vanilla Ice Cream with Cherry Dark Chocolate Ice Cream</option>
                    <option>Vanilla Ice Cream with Pistachio</option>
                </select>
            </div>
            <div class="col-2">
                <select class="form-control" id="quantity">
                    <option>1</option>
                    <option>1.5</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                </select>
            </div>
            <div class="col-2">
                <div id="totalAmount"></div>
            </div>
            <div class="col-2">
                <div>
                    <img class="imageDisplay" id="iceCreamImage" alt="">
                </div>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-5">
            <form method="post" enctype="multipart/form-data" asp-action="Buy">
                <div class="form-group row">
                    <label asp-for="FirstName" class="col-sm-4 col-form-label"></label>
                    <div class="col-sm-6">
                        <input asp-for="FirstName" type="text" class="form-control" placeholder="First Name" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="LastName" class="col-sm-4 col-form-label"></label>
                    <div class="col-sm-6">
                        <input asp-for="LastName" type="text" class="form-control" placeholder="Last Name" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Address" class="col-sm-4 col-form-label"></label>
                    <div class="col-sm-6">
                        <input asp-for="Address" type="text" class="form-control" placeholder="Address" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Email" class="col-sm-4 col-form-label"></label>
                    <div class="col-sm-6">
                        <input asp-for="Email" type="email" class="form-control" placeholder="email@example.com" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="PhoneNumber" class="col-sm-4 col-form-label"></label>
                    <div class="col-sm-6">
                        <input asp-for="PhoneNumber" type="number" class="form-control" placeholder="Phone Number" required>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-10">
                        <button id="formButton" type="submit" class="btn btn-outline-primary">
                            Make a Purchase
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

day04/mod9/IceCreamCompany/IceCreamCompany/Views/IceCream/Index.cshtml
@model IEnumerable<IceCreamCompany.Models.IceCream>

@{
    ViewData["Title"] = "Index";
}

<h1>Choose your favourite one</h1>
<div class="img-container">
    @foreach (var item in Model)
    {
        <div class="item">
            <h3>
                @Html.DisplayFor(modelItem => item.Flavor)
            </h3>
            @if (item.PhotoFileName != null)
            {
                <div>
                    <img src="@Url.Action("GetImage", "IceCream", new { iceCreamId = item.IceCreamId })" />
                </div>
            }
            <div>
                <p>
                    @Html.DisplayFor(model => item.Price)
                </p>
            </div>
        </div>
    }
</div>

day04/mod9/IceCreamCompany/IceCreamCompany/Views/IceCream/ThankYou.cshtml
@{
    ViewData["Title"] = "ThankYou";
}

<h1>
    Thanks for your purchase and hope you enjoy the ice cream!
</h1>